/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false` (hash: f834ba8eb56f750667061b2964d71f5c)
interface __BaseEnv_Env {
	AIRING_CAL_R2: R2Bucket;
	AIRING_CAL_DATA_R2: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
