name = "airing-cal-read"
main = "src/index.ts"
compatibility_date = "2026-06-17"
keep_vars = true

[[kv_namespaces]]
binding = "AIRING_CAL_KV"
id = "airing-cal-kv"

[[r2_buckets]]
binding = "AIRING_CAL_R2"
bucket_name = "airing-cal-images"
