name = "airing-cal-media"
main = "src/index.ts"
compatibility_date = "2026-06-17"

[[kv_namespaces]]
binding = "AIRING_CAL_KV"
id = "airing-cal-kv"

[[r2_buckets]]
binding = "AIRING_CAL_R2"
bucket_name = "airing-cal-images"

[[queues.consumers]]
queue = "airing-cal-media"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
