/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false` (hash: fc6da43fc86b2d9fd695c8f48c8904c1)
interface __BaseEnv_Env {
	READ_WORKER: Fetcher /* airing-cal-read */;
	SYNC_WORKER: Fetcher /* airing-cal-sync */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
